### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

### ISSUE THREAD

**Issue by kricket104103** [Technowlogy-Pushpender/crypter#4]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\Krickets Laptop\.spyder-py3\untitled0.py", line 11, in <module>
    shark=pd.read_csv(r'C:\DATA QUALITY\SharkAttackMod4.csv')

  File "C:\Users\Krickets Laptop\anaconda3\lib\site-packages\pandas\io\parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)

  File "C:\Users\Krickets Laptop\anaconda3\lib\site-packages\pandas\io\parsers.py", line 454, in _read
    data = parser.read(nrows)

  File "C:\Users\Krickets Laptop\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1133, in read
    ret = self._engine.read(nrows)

  File "C:\Users\Krickets Laptop\anaconda3\lib\site-packages\pandas\io\parsers.py", line 2037, in read
    data = self._reader.read(nrows)

  File "pandas\_libs\parsers.pyx", line 859, in pandas._libs.parsers.TextReader.read

  File "pandas\_libs\parsers.pyx", line 874, in pandas._libs.parsers.TextReader._read_low_memory

  File "pandas\_libs\parsers.pyx", line 951, in pandas._libs.parsers.TextReader._read_rows

  File "pandas\_libs\parsers.pyx", line 1083, in pandas._libs.parsers.TextReader._convert_column_data

  File "pandas\_libs\parsers.pyx", line 1136, in pandas._libs.parsers.TextReader._convert_tokens

  File "pandas\_libs\parsers.pyx", line 1253, in pandas._libs.parsers.TextReader._convert_with_dtype

  File "pandas\_libs\parsers.pyx", line 1268, in pandas._libs.parsers.TextReader._string_convert

  File "pandas\_libs\parsers.pyx", line 1458, in pandas._libs.parsers._string_box_utf8

**Comment by hamza-saeedCys** [comment]
try  .decode('latin1') instead of decode('utf-8')
